### ISSUE TITLE
passing a negative div_thresh value to pcair.R

### ISSUE THREAD

**Issue by HanleyKingston** [Blue-Lab/assoc_pipeline#20]
the div_thresh value should be negative but I can't find a way to pass the command line a negative argument:
"Invalid argument value: expecting numeric but got: (-0.0442)"
I also tried passing it a string and converting that to numeric in the script but that didn't work.
It would be really nice to be able to give it a function like 2^(-4.5)
Thanks!

**Comment by broomej** [comment]
It looks like this might be related to an issue with argparser being able to handle negative numeric values, but it was supposedly fixed in [v 0.5.1](https://bitbucket.org/djhshih/argparser/src/master/). I'll see about making a minimal example.

I did get this to work by changing it to a positive value (or expression) and multiplying it by -1 inside the script, but I'm not crazy about that solution

**Comment by broomej** [comment]
I posted this in slack, but reposting here for posterity:
> There’s a bug that was fixed in v 0.5 of argparser that has again reared it’s ugly head in v0.6 that has issues with parsing negative numeric arguments. It’s fixed in 0.6.1 but not yet available on CRAN. are there any objections to me installing it to our shared library from the author’s bit bucket?

**Comment by broomej** [comment]
I installed argparser v0.6.1 to /nfs/beluga0_home/MasterLibrary which should fix the issue
